project_id = "fgosozxvhbdhqigwzqih"

[functions.generate-checklists]
verify_jwt = false

[functions.generate-tasks]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true

[functions.api-v1]
verify_jwt = false
